[Trivial] Add backup-id to 'size' param info
Specifying size is not required while providing --backup-id.
Also When we don't provide the size the output turns out to be
error: Size is a required parameter if snapshot or source
volume or backup is not specified.
which should be modified in 'size' info too.

Change-Id: Ia250df37db9170757d5f834d516781e04582f08b