Fix broken argument name in v2 volume extend routine
The new_size attribute was misspelled, causing the volume extend
operation to fail with:

    ERROR: 'Namespace' object has no attribute 'new_size'

This happens only with the v2 API, v1 works fine.

Change-Id: Icb6b5008dad229f21e7906d9b5342d41f5e760cd
Closes-Bug: #1259552