Python3.11: Fix argparse-related test failures
In Python3.11, the following code crashes:

$ cat test.py
import argparse

parser = argparse.ArgumentParser(description='Short sample app')
subparsers = parser.add_subparsers()
subparsers.add_parser('foo')
subparsers.add_parser('foo')

$ python3.11 test.py
Traceback (most recent call last):
  File "/tmp/arg.py", line 6, in <module>
    subparsers.add_parser('foo')
  File "/usr/lib/python3.11/argparse.py", line 1197, in add_parser
    raise ArgumentError(self, _('conflicting subparser: %s') % name)
argparse.ArgumentError: argument {foo}: conflicting subparser: foo

It is now forbidden to use add_parser() multiple times with the same
arguments, which is exactly what we do in the following tests:

- cinderclient.tests.unit.test_shell.TestLoadVersionedActions.test_load_versioned_actions
- cinderclient.tests.unit.test_shell.TestLoadVersionedActions.test_load_actions_with_versioned_args

In order to fix the tests failures, we make sure to reset the parser and
subparsers before calling add_parser().

While not strictly necessary, we split those tests into two functions,
for readability purposes.

Closes-Bug: #1983054
Change-Id: I2d4cb81a394f3c10e5f01945d894746a904fb5df