Print backtrace for exception when in debug mode
If the cinder shell is run in debug mode
(CINDERCLIENT_DEBUG is set in the environment or
with --debug), print a traceback for unhandled
exceptions.

This makes it possible to debug issues like this:
  $ cinder credentials
  ERROR: list indices must be integers, not str

Related-Bug: #1631142

Co-Authored-By: Gorka Eguileor <geguileo@redhat.com>
Change-Id: I5e9b3283602d404ab43494f15d57ec5abbcd77dc