Fix cinder command execution issue with a token
This commit fixes the issue where the following error occurs when
executing cinder commands using a token:
> ERROR: argument --os-token: conflicting option string: --os-token

This issue arises because `os_token` is added to the parser in
`keystoneauth1.loading.register_auth_argparse_arguments()`, and then
`os_token` is set again by `parser.add_argument('--os-token')`.

Closes-Bug: #2061349
Change-Id: I8d1ff0f202bec24ed2982108b6cbba1b7981b356